#pragma once

#include "config.h"
#include <HardwareTimer.h>

#include "Hardware/SystemClock.h" // Required for SystemClock::GetInstance().GetPClk2Freq() in .cpp

namespace STM32Step
{
    // Forward declaration
    class Stepper;

    /**
     * @class TimerControl
     * @brief Static class to manage the hardware timer (TIM1) for generating hardware stepper pulses.
     *
     * This class handles the initialization and control of TIM1 in PWM mode to generate
     * precise, jitter-free step pulses for the stepper motor driver without CPU intervention for each pulse.
     */
    class TimerControl
    {
    public:
        /**
         * @enum MotorState
         * @brief Defines the operational state of the timer/motor control system.
         */
        enum class MotorState
        {
            IDLE,    ///< Motor/Timer is idle.
            RUNNING, ///< Motor/Timer is actively running.
            ERROR    ///< An error has occurred in timer setup.
        };

        /**
         * @brief Initializes the hardware timer (TIM1) for hardware PWM pulse generation.
         * This must be called once before any stepper operations.
         */
        static void init();

        /**
         * @brief Starts or resumes the hardware timer PWM output.
         * @param stepper Pointer to the Stepper object being controlled.
         */
        static void start(Stepper *stepper);

        /**
         * @brief Stops or pauses the hardware timer PWM output.
         */
        static void stop();

        /**
         * @brief Signals an emergency stop condition.
         */
        static void emergencyStopRequest();

        /**
         * @brief Sets the frequency of the hardware-generated step pulses.
         * @param frequency_hz The target frequency in Hz.
         */
        static void setFrequency(uint32_t frequency_hz);

        /**
         * @brief Sets the exact number of pulses to generate.
         * Uses the Repetition Counter (RCR) for precise move counts.
         * @param pulses The number of pulses to generate. Set to 0 for continuous output.
         */
        static void setPulseCount(uint32_t pulses);

        /**
         * @brief Gets the accumulated pulse count from the hardware slave timer (TIM5).
         * This counter increments for every pulse generated by TIM1, regardless of direction.
         * @return The raw 32-bit counter value.
         */
        static uint32_t getPulseCount();

        // --- Public Static Members ---
        /** @brief Pointer to the HardwareTimer instance (e.g., TIM1). Managed internally. */
        static HardwareTimer *htim;

        /** @brief Pointer to the current stepper instance being controlled. */
        static Stepper *currentStepper;

        /** @brief Gets the current operational state of the TimerControl. @return MotorState */
        static MotorState getCurrentState() { return currentState; }

    private:
        /**
         * @brief The static ISR handler for the timer's update event.
         * This is called by the Arduino framework via attachInterrupt.
         */
        static void pulse_isr();

        /**
         * @brief Initializes the GPIO pin for the TIM1 PWM output channel.
         */
        static void initGPIO_PWM();

        // State tracking
        static volatile MotorState currentState; ///< Current state of the TimerControl.
        static volatile bool emergencyStop;      ///< Flag indicating an emergency stop has been requested.
    };

} // namespace STM32Step
